export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRY = "GET_COUNTRY"
export const SEARCH_NAME = "SEACH_NAME"
export const FILTER_CONTINENTS = "FILTER_CONTINENTS"
export const RESET_STATE = "RESET_STATE"
export const ORDER_ALPHABETIC = "ORDER_ALPHABETIC"







