export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRY = "GET_COUNTRY"
export const SEARCH_NAME = "SEACH_NAME"
export const ORDER_COUNTRIES = "ORDER_COUNTRIES"
export const FILTER_CONTINENTS = "FILTER_CONTINENTS"
export const RESET_FILTERS = "RESET_FILTERS"
export const ORDER_ALPHABETICAL = "ORDER_ALPHABETICAL"





