export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRY = "GET_COUNTRY"
export const SEARCH_NAME = "SEACH_NAME"
export const FILTER_CONTINENTS = "FILTER_CONTINENTS"
export const ORDER_ALPHABETICAL = "ORDER_ALPHABETICAL"








